### ISSUE TITLE
Incorrect Layout on Issues for Redmine 3.2.0.stable

### ISSUE THREAD

**Issue by alxRlja** [hardpixel/minelab#18]
Hi! 
I think the theme is beautiful, but I have found a small issue when testing it. it seems that for Redmine 3.2.0, the layout in the issues page is incorrect. Fields appear below the labels (Attached image). I assume this is because Redmine 3.2.0 work with DIV's instead of tables. 

![2016-01-18_11-26-35](https://cloud.githubusercontent.com/assets/2036996/12398148/6227343e-bdd7-11e5-98b5-65c8da7e9b4e.png)

Thank you! 
-Alex

**Comment by goutnet** [comment]
I checked on my installation, no problem here …

Can you check again on redmine 3.3 with last master?

**Comment by alxRlja** [comment]
Hello!, 

Tested on Redmine 3.3.0.stable, it work pretty well now. 

Thank you very much! 

-Alex

**Comment by goutnet** [comment]
@jonian I think you can close this issue :)

**Comment by alxRlja** [comment]
ho! right! sorry, busy day.  :-)
