### ISSUE TITLE
Collapse - Sidebar

### ISSUE THREAD

**Issue by Niremizov** [hardpixel/minelab#23]
Hello,

Is it possible to collapse a sidebar (https://yadi.sk/i/cYUiI3FGrqHi2) or there is no such ability and we need to commit it?

**Comment by bes1002t** [comment]
as I know there is no possibility to do this yet. But it should be not difficult to implement such a feature.

**Comment by aman1792** [comment]
**Yes, it would be helpful if you can fold +++**

**Comment by Niremizov** [comment]
Made a Pull Request https://github.com/hardpixel/minelab/pull/24/files - it solves to issues but pretty ugly.
