### ISSUE TITLE
Redmine 3.3.0: styling glitch in issue comments

### ISSUE THREAD

**Issue by ageis** [hardpixel/minelab#25]
The latest version of Redmine has apparently changed the appearance of the functionality for quoting, editing and removing comments. With the Minelab theme, I'm seeing an undesirable scrollbar on some comments, because of `overflow: auto` on `.splitcontent, div.journal, .syntaxhl .code pre`.

![redmine_edits](https://cloud.githubusercontent.com/assets/1161532/16467436/255d559c-3dfc-11e6-8045-2042c859c50f.png)

You can make the unwanted overflow scrollbar disappear if you change `top: 1.6em` in `#main #content .contextual` (line 4713 of application.css) to `top: 1em`, but I would look at it further to ensure the spacing and positioning of the contextual buttons is as desired.

**Comment by undigo** [comment]
in my application.css file,the `top: 1.6em` is on line 4703.
perfect thanks !

**Comment by goutnet** [comment]
I think I just fixed this in #30
