### ISSUE TITLE
progress_bar.gif not found

### ISSUE THREAD

**Issue by goutnet** [hardpixel/minelab#27]
Hi, 

I get this in my logs when using this theme and trying to upload a file:

`ActionController::RoutingError (No route matches [GET] "/themes/hardpixel-minelab/stylesheets/images/progress_bar.gif")`

not sure which progress_bar.gif you are using :/

**Comment by goutnet** [comment]
Well that one is still there :/ I did not fix it since I don't have the asset? (the gif file). Should I fix it another way? (like bootstrap does for instance)?

**Comment by jonian** [comment]
I removed the style. It was from jquery ui progressbar but it seems that it is not used.

https://github.com/jquery/jquery-ui/blob/1.8.7/themes/base/jquery.ui.progressbar.css

**Comment by goutnet** [comment]
ok I just saw you did this here: 6dcb7b3fdbf08e8d8ecf2aa3bf811959eaf07680￼ nevermind that comment :)

**Comment by jonian** [comment]
BTW thanks for your pull requests.

**Comment by goutnet** [comment]
You're welcome, I'd like to fix a few more bugs in this weekend so do not hesitate to test more (and create issues here, I have subscribed to issues).

I will also add support for some plugins: Accept plugin and work on the SCRUM plugin styling as well (using it here).

Eventually I might also work on a better configuration of colors and logo (will create an issue on that to let you know).
