### ISSUE TITLE
include feature - Drag'n'drop order configuration for statuses, trackers, roles

### ISSUE THREAD

**Issue by pkestefran** [hardpixel/minelab#40]
Hello, 
recently I have discovered this great theme and noticed that it is missing a [great UI feature](https://www.redmine.org/issues/12909) added to redmine in 3.3.0. 

I have adjusted the scss files to show the sort-handle in minelab theme as well.

(Please note that this may not be the best applicable solution, because Im repeating some blocks of code especially from `a { ... }`, but considering that sort-handle is not a link I coudlnt find a better solution as Im quite new to scss)

**added in _icons.scss**
`.fa-arrows-v:before {
  content: "\f07d";
}`

**in application.scss** 
added `.sort-handle` to line:
`.icon, [class*="icon-"], #context-menu li a { ....`

also i have added

```
.sort-handle {
  cursor: pointer;
  color: $link-color;
  @include transition-duration(0.3s);
  text-decoration: none;
  font-size: 1em;
  display: inline-block;
  margin-right: 0.5em;
  @extend .fa-arrows-v;

  &:hover, &:active, &:focus {
    color: $link-color-hover;
  }

  &:after {
    content: "Sort";
  }
  &:before {
    @extend .fa;

    margin-right: 0.5em;
    vertical-align: middle;
  }
}
```

**Comment by goutnet** [comment]
Can you issue a pull request for this change so I can review it and merge it?

**Comment by goutnet** [comment]
merged => close
