### ISSUE TITLE
history show as time-line

### ISSUE THREAD

**Issue by joaoverissimo** [hardpixel/minelab#43]
Hello, 

I want to suggest a css for the history task stand as a time-line.

.journal {padding-left: 34px;border-left: 1px solid #ccc;}
.journal h4::before {content: "";width: 13px;height: 13px;background: #ccc;display: block;border-radius: 50%;position: absolute;left: -5px;}
.journal h4 {border: 0px;padding: 0px;margin-left: -20px;}

![2016-11-05_18h20_23](https://cloud.githubusercontent.com/assets/2000159/20033301/9d615050-a384-11e6-907f-7331957da08a.png)

**Comment by goutnet** [comment]
nice, I like the idea, let me check that later today.

**Comment by goutnet** [comment]
I think it would be a nice idea to do so, can you try to make a pull request with this?

**Comment by goutnet** [comment]
In fact, don't bother doing it, i just implemented it :)

**Comment by joaoverissimo** [comment]
great
