### ISSUE TITLE
Shall we release v0.3?

### ISSUE THREAD

**Issue by goutnet** [hardpixel/minelab#44]
@jonian I think we are getting close to a working version here.

Here are a few stuff I would like to have on v0.3:

1. All colors usage either moved to variables.less or derived from it
2. A clean way to update a customized theme
3. No more glitches from the main theme

At least 3. seems to be done, (as nobody seems to be reporting any more issues…).

What are your thoughts?

**Comment by jonian** [comment]
Hi @goutnet, sorry for the late response, I have been very busy lately.
Feel free to release a new version when you think we should.

**Comment by goutnet** [comment]
Ok then, I will create a few issues on the things I want to be in v0.3 then release when done.
