### ISSUE TITLE
Overrides Do Not Work

### ISSUE THREAD

**Issue by jwbearden** [hardpixel/minelab#57]
This theme is very nice; however, custom overrides do not work.

The documents is a bit "light", but I believe I'm applying the appropriate process for overrides.  The changes are not reflected.

What am I doing wrong?  Does anyone have a simple example?

**Comment by goutnet** [comment]
you need to rebuild the css after each modification, (using the build.sh script), did you do so?

**Comment by jwbearden** [comment]
Yes.  I was rebuilding - seems to have related to now having certain gems installed that are required for rebuilding the CSS.   Ran bundle install from the theme directory and seems to be working now.

Thank  you!
