### ISSUE TITLE
Forked to fix

### ISSUE THREAD

**Issue by NemesisRE** [hardpixel/minelab#6]
Hi,
I really like your theme!

I forked it to fix issues I see/saw cause it seems you don't have time at the moment. When you start developing again just give me a hint and I would be happy to send you a pull request.

Cheers
Steven

**Comment by olibia** [comment]
Hi Steven,

I'm glad you like it. It's true, we are working on other projects at this time. We plan to continue developing, but don't know when.

Feel free to make any modifications you see right, it's really helpful.

Thanks,
Olibia
