### ISSUE TITLE
Guard does not work - cannot update theme

### ISSUE THREAD

**Issue by MatthewPaulGithub** [hardpixel/minelab#60]
First of all thanks for creating this theme. I honestly think it's the best one out there in terms of a clean 'modern' look for users. I still like the html look for myself for speed, but having a SASS theme like this makes it much easier to show non-tech end users. Awesome.

Having said that I use a lot of plugins, particularly the custom menu plugin - http://www.redmine.org/plugins/custom_menu - so sometimes things don't show up on that menu, or they don't have icons under setup. So I'd like to do some simple additions. But, when I try to do bundle install per your instructions so I can then run guard, I get -

bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the
current version, ruby 2.1.10p492

So I can't go any further.  I am running a standard bitnami redmine stack on an amazon ec2 server. So no chance of updating ruby. Is there another way I can do easy updates?  Like a public server or something?   I'd set one up if I knew what was needed, this is just such a good theme I'd like to work on it if I could.

**Comment by jonian** [comment]
Apologies for the late response. I removed Gemfile.lock from version control. This should fix your issue.
