### ISSUE TITLE
Style Problems

### ISSUE THREAD

**Issue by danieldaeschle** [hardpixel/minelab#64]
Can anyone tell me why some styles are incorrect?
![image](https://user-images.githubusercontent.com/30751516/33068076-74fb7c0a-ceb0-11e7-8495-87f3f3c2cc11.png)
![image](https://user-images.githubusercontent.com/30751516/33068093-8230724a-ceb0-11e7-8463-dc1acaaec811.png)

Something is wrong.... please help!

**Comment by jonian** [comment]
Hi, this theme is not compatible with redmine 3.x series. As stated in the readme, this theme supports version 2.5.x.
