### ISSUE TITLE
login/register link disappear on login page

### ISSUE THREAD

**Issue by RikyTres** [hardpixel/minelab#8]
I can find the link to login and register page on the top-right of the main bar.

With the default theme it's visible but with minelab theme it's not.
See the screenshot for mode details...

![schermata 2015-10-12 alle 13 02 07](https://cloud.githubusercontent.com/assets/2545471/10426620/2fc14fa8-70e2-11e5-864d-9ccebd124b66.png)
![schermata 2015-10-12 alle 13 02 58](https://cloud.githubusercontent.com/assets/2545471/10426621/2fee9a3a-70e2-11e5-8cdc-f152125cfd49.png)

**Comment by RikyTres** [comment]
Looking inside the code: The elements is there, but they have 0px with.
Looks like you don't want to show them.

**Comment by zzvv** [comment]
+1
